# Generated by Django 4.1.1 on 2022-09-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_contact_name_remove_contact_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
